#!/bin/bash
 
ARCH=arm \
CC=arm-linux-gnueabi-gcc ./configure \
CHECK_CFLAGS="-I/tmp/mc_build/builds/build_check-0.10.0/include/" \
CHECK_LIBS="-L/tmp/mc_build/builds/build_check-0.10.0/lib/ -lcheck" \
GLIB_CFLAGS="-I/tmp/mc_build/builds/build_glib-2.44.1/include/glib-2.0 -I/tmp/mc_build/builds/build_glib-2.44.1/lib/glib-2.0/include" \
GLIB_LIBS="-L/tmp/mc_build/builds/build_glib-2.44.1/lib -lglib-2.0" \
GMODULE_CFLAGS="-I/tmp/mc_build/builds/build_glib-2.44.1/include/glib-2.0 -I/tmp/mc_build/builds/build_glib-2.44.1/lib/glib-2.0/include" \
GMODULE_LIBS="-L/tmp/mc_build/builds/build_glib-2.44.1/lib/glib-2.0 -lgmodule-2.0" \
--host=arm-linux-gnueabi \
--prefix=/tmp/mc_build/builds/build_mc-4.8.14 \
--enable-static=yes \
--with-screen=ncurses \
--with-ncurses-includes="/tmp/mc_build/builds/build_ncurses-5.9/include" \
--with-ncurses-libs="/tmp/mc_build/builds/build_ncurses-5.9/lib"
make -j3
sudo make install
