#!/bin/bash
ARCH=arm \
CC=arm-linux-gnueabi-gcc ./configure \
--target=arm-linux-gnueabi \
--with-gcc=arm-linux-gnueabi-gcc \
--host=arm-linux-gnueabi \
--prefix=/tmp/mc_build/builds/build_ncurses-5.9 \
--enable-static=yes
make
sudo make install
